import type { Item } from './types';
import { subDays, addDays, formatISO } from 'date-fns';

export const items: Item[] = [
  {
    id: '1',
    name: 'Wheelchair',
    category: 'Medical Equipment',
    description: 'Standard wheelchair for mobility assistance.',
    imageUrl: 'https://picsum.photos/seed/wheelchair/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 40)),
    issuedTo: 'Fathima K (123-456-7890)',
    issueDate: formatISO(subDays(new Date(), 10)),
    expectedReturnDate: formatISO(addDays(new Date(), 5)),
  },
  {
    id: '2',
    name: 'Crutches',
    category: 'Medical Equipment',
    description: 'A pair of adjustable crutches.',
    imageUrl: 'https://picsum.photos/seed/crutches/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 60)),
  },
  {
    id: '3',
    name: 'Hospital Bed',
    category: 'Medical Furniture',
    description: 'Adjustable hospital bed for home care.',
    imageUrl: 'https://picsum.photos/seed/medbed/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 15)),
  },
  {
    id: '4',
    name: 'Oxygen Cylinder',
    category: 'Medical Equipment',
    description: 'Portable oxygen cylinder with regulator.',
    imageUrl: 'https://picsum.photos/seed/oxygen/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 90)),
  },
  {
    id: '5',
    name: 'Walker',
    category: 'Mobility Aid',
    description: 'Walker for elderly and patient support.',
    imageUrl: 'https://picsum.photos/seed/walker/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 25)),
  },
  {
    id: '6',
    name: 'Wheelchair 2',
    category: 'Medical Equipment',
    description: 'Standard wheelchair for mobility assistance.',
    imageUrl: 'https://picsum.photos/seed/wheelchair2/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 50)),
    issuedTo: 'Aisha P (345-678-9012)',
    issueDate: formatISO(subDays(new Date(), 2)),
    expectedReturnDate: formatISO(addDays(new Date(), 12)),
  },
  {
    id: '7',
    name: 'Oxygen Concentrator',
    category: 'Medical Equipment',
    description: 'Electric oxygen concentrator for home use.',
    imageUrl: 'https://picsum.photos/seed/concentrator/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 120)),
    issuedTo: 'Ibrahim S (456-789-0123)',
    issueDate: formatISO(subDays(new Date(), 20)),
    expectedReturnDate: formatISO(subDays(new Date(), 1)), // Overdue
  },
];
