import type { Item } from './types';
import { subDays, addDays, formatISO } from 'date-fns';

export const items: Item[] = [
  {
    id: '1',
    name: 'Wheelchair',
    itemCode: 'WCHR01',
    description: 'Standard wheelchair for mobility assistance.',
    imageUrl: 'https://picsum.photos/seed/wheelchair/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 40)),
    recipientName: 'Fathima K',
    recipientMobile: '1234567890',
    issuerName: 'Admin',
    issueDate: formatISO(subDays(new Date(), 10)),
    expectedReturnDate: formatISO(addDays(new Date(), 5)),
  },
  {
    id: '2',
    name: 'Crutches',
    itemCode: 'CRCH01',
    description: 'A pair of adjustable crutches.',
    imageUrl: 'https://picsum.photos/seed/crutches/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 60)),
  },
  {
    id: '3',
    name: 'Hospital Bed',
    itemCode: 'HOSB01',
    description: 'Adjustable hospital bed for home care.',
    imageUrl: 'https://picsum.photos/seed/medbed/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 15)),
  },
  {
    id: '4',
    name: 'Oxygen Cylinder',
    itemCode: 'OXYC01',
    description: 'Portable oxygen cylinder with regulator.',
    imageUrl: 'https://picsum.photos/seed/oxygen/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 90)),
  },
  {
    id: '5',
    name: 'Walker',
    itemCode: 'WLKR01',
    description: 'Walker for elderly and patient support.',
    imageUrl: 'https://picsum.photos/seed/walker/400/300',
    status: 'Available',
    dateAdded: formatISO(subDays(new Date(), 25)),
  },
  {
    id: '6',
    name: 'Wheelchair 2',
    itemCode: 'WCHR02',
    description: 'Standard wheelchair for mobility assistance.',
    imageUrl: 'https://picsum.photos/seed/wheelchair2/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 50)),
    recipientName: 'Aisha P',
    recipientMobile: '3456789012',
    issuerName: 'Volunteer A',
    issueDate: formatISO(subDays(new Date(), 2)),
    expectedReturnDate: formatISO(addDays(new Date(), 12)),
  },
  {
    id: '7',
    name: 'Oxygen Concentrator',
    itemCode: 'OXYC02',
    description: 'Electric oxygen concentrator for home use.',
    imageUrl: 'https://picsum.photos/seed/concentrator/400/300',
    status: 'Issued',
    dateAdded: formatISO(subDays(new Date(), 120)),
    recipientName: 'Ibrahim S',
    recipientMobile: '4567890123',
    issuerName: 'Admin',
    issueDate: formatISO(subDays(new Date(), 20)),
    expectedReturnDate: formatISO(subDays(new Date(), 1)), // Overdue
  },
];
